package mx.insoftec.model;
// Generated 14/06/2018 10:15:38 AM by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int id;
     private String rfc;
     private String razonSocial;
     private String activo;

    public Cliente() {
    }

	
    public Cliente(int id) {
        this.id = id;
    }
    public Cliente(int id, String rfc, String razonSocial, String activo) {
       this.id = id;
       this.rfc = rfc;
       this.razonSocial = razonSocial;
       this.activo = activo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }




}


